<a href="https://colab.research.google.com/github/SRIROSSAAISYAHPUTERIBAHARIE/PSDS-5.0/blob/main/Operasi_Numpy_dan_Matriks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**SRI ROSSA AISYAH PUTERI BAHARIE**
#**2100015052**
**PERTEMUAN 12**

#**Numpy Array**

Numpy merupakan salah satu libary Phyton yang banyak digunakan dalam proses analisis data karena fiturnya yang hebat.

In [1]:
import numpy as np

#**Membuat Array Numpy**

Kita bisa membuat Array menggunakan Numpy dengan membungkusnya terlebih dahulu di list dan diubah menjadi numpy array.

In [2]:
List_1 = [1, 2, 3, 4, 5]
arr_1 = np.array([List_1])
arr_1

array([[1, 2, 3, 4, 5]])

Beberapa fungsi yang dapat digunakan membuat array.

```zeros()  -> Membuat array dengan nilai 0```

```ones()     -> Membuat array dengan nilai 1```

```arange()   -> Membuat array dengan nilai dalam range```

```linspace()  -> Membuat array dengan nilai dalam interval```

```logspace() -> Membuat array dengan nilai log Base10 dalam interval```

```full       -> Membuat array dengan semua elemen penyusunnya sama```

```full_like  -> Membuat array dengan semua elemen penyusunnya sama namun ukurannya dari array lainnya```

```identity   -> Membuat array matriks identitas```

```repeat     -> Membuat array dengan perulangan array atau seuence```

In [3]:
#Membuat array dengan nilai 0 dengan shape (5, 5)
print(np.zeros((2, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
#Membuat array dengan nilai 1 dengan shape (5, 3)
print(np.ones((5, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#Arange (start, stop, step)
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [7]:
#Linespace(start, stop, number)
print(np.linspace(1, 10, 3))

[ 1.   5.5 10. ]


In [8]:
#Longspace(start, stop, number)
print(np.logspace(1, 10, 2))

[1.e+01 1.e+10]


In [9]:
#Membuat array matriks dengan shape (2, 2) dengan elemen 99
print(np.full((2, 2), 4))

[[4 4]
 [4 4]]


In [10]:
#Membuat array matriks dengan shape yang sama dengan A dengan semua elemennya 4
A = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(A)
print(np.full_like(A, 3))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3]]


In [11]:
#Random decimal numbers
print(np.random.rand(4,2))

[[0.756098   0.99763701]
 [0.09098937 0.0049467 ]
 [0.56171137 0.89471555]
 [0.20286195 0.93605411]]


In [12]:
#Random Integer values
print(np.random.randint(-4,8, size=(3,3)))

[[ 4  7 -4]
 [ 0 -1  2]
 [ 2  4  6]]


In [13]:
#Membuat matriks identitas
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [14]:
#Membuat matriks dengan perulangan array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


#**Metode-metode pada Array**

Objek array pada Phyton Numpy memiliki berbagai method untuk melakukan operasi atau perintah-perintah tertentu. Berikut adalah fungsi-fungsi yang merupakan metode pada array yang sering dipakai :

**array.ndim**

Metode ini digunakan untuk mengetahui dimensi dari array.

In [15]:
a = np.array([29, 28, 30], dtype='int32')
print(a)

print("Dimensi dari array a adalah : ", a.ndim)

[29 28 30]
Dimensi dari array a adalah :  1


***array.shape**

Metode ini digunakan untuk mengetahui ukuran (variabel dan baris) dari array.

In [17]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

print("Ukuran Shape dari array b adalah : ", b.shape)

[[9. 8. 7.]
 [6. 5. 4.]]
Ukuran Shape dari array b adalah :  (2, 3)


**array.dtype**

Metode ini digunakan untuk mengetahui type data dari elemen penyusun array.

In [18]:
a.dtype

dtype('int32')

**array.size**

Metode ini digunakan untuk menghitung jumlah elemen dari array.

In [19]:
a.size

3

#**Multidimensional Array**

Salah satu fitur menarik dari NumPy adalah dia mampu membuat multidimensional array dan melakukan manipulasi array dengan
mudah dan cepat.

Multidimensional array adalah array yang berbentuk lebih dari 1 dimensi (1D), bisa 2D, 3D, 4D dan seterusnya.

Cara membuat multidimensional array sama dengan membuat array 1 dimensi, perbedaannya hanya pada parameter yang
digunakan.

Berikut contohnya membuat array 2 dimensi

In [20]:
arr_2 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

Array diatas adalah berbentuk (2, 5) artinya mempunyai 2 baris dan 5 kolom.

Kita bisa melihat jumlah elemen di setiap dimensi dengan menggunakan shape.

In [21]:
arr_2.shape

(2, 5)

#**Indexing dan Slicing**

Kita juga dapat melakukan indexing dan slicing terhadap array dengan mudah
Indexing dimulai dari 0 dan dimulai dengan notasi bracket “[ ]”
Misal kita ingin mencari nilai yang berada di index 0, 2, dan 4.

In [22]:
arr_3 = np.array([1, 2, 3, 4, 5])
print(arr_3[0])
print(arr_3[2])
print(arr_3[4])

1
3
5


Untuk mengambil nilai berderet tambahkan ":"

In [23]:
arr_3 = np.array([1, 2, 3, 4, 5])
print(arr_3[0:4])

[1 2 3 4]


In [24]:
arr_4 = np.array([[1, 2, 3, 4, 5], [2, 4, 6, 8, 10]])
print(arr_4)
print(arr_4[1, 3])

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]]
8


Nilai pada kolom index ke-1 dan baris index ke-1 adalah 4.

#**Operasi Aritmatika**

Kita bisa menggunakan operasi aritmatika seperti penjumlahan, pengurangan, perkalian, pembagian dan perpangkatan
Operator yang digunakan adalah +, -, , / dan *

Berikut contoh operasi aritmatika pada array :

In [25]:
arr_A = np.array([1, 2, 3, 4, 5])
arr_B = np.array([2, 2, 2, 2, 2])

print("Penjumlahan = ", arr_A + arr_B)
print("Pengurangan = ", arr_A - arr_B)
print("Perkalian = ", arr_A * arr_B)
print("Pembagian = ", arr_A / arr_B)
print("Perpangkatan = ", arr_A ** arr_B)

Penjumlahan =  [3 4 5 6 7]
Pengurangan =  [-1  0  1  2  3]
Perkalian =  [ 2  4  6  8 10]
Pembagian =  [0.5 1.  1.5 2.  2.5]
Perpangkatan =  [ 1  4  9 16 25]


#**Operasi Matematika**

NumPy mempunyai fungsi matematika yang dapat digunakan pada Array.

Beberapa contoh fungsi statistik antara lain min(), max(), mean(), sum(), std().


In [26]:
arr_5 = np.array([1, -2, 3, 4, 5])
print("Nilai minimal = ", arr_5.min())
print("Nilai maksimal = ", arr_5.max())
print("Nilai rata-rata = ", arr_5.mean())
print("Total nilai = ", arr_5.sum())
print("Standar Deviasi = ", arr_5.std())

Nilai minimal =  -2
Nilai maksimal =  5
Nilai rata-rata =  2.2
Total nilai =  11
Standar Deviasi =  2.4819347291981715


Ada juga fungsi argmin() dan argmax() untuk mendapatkan index dari nilai minimum dan maksimum.

In [27]:
print("Index nilai niminal = ", arr_5.argmin())
print("Index nilai maksimal = ", arr_5.argmax())

Index nilai niminal =  1
Index nilai maksimal =  4


#**Transformasi Array**

Kita dapat membuat array baru dari array yang sudah ada melalui berbagai metode transformasi seperti merubah ukuran,
menggabungkan dua array atau lebih dan lain sebagainya.


**array.reshape**

Metode ini digunakan untuk merubah shape array dengan jumlah elemen yang tidak berubah.


In [28]:
sebelum = np.array([[1,2,3,4],[5,6,7,8]])
print(sebelum)
sesudah = sebelum.reshape((8,1))
print(sesudah)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


Perhatikan bahwa array sebelum memiliki jumlah elemen 8 (2, 4) dan array sesudah juga memiliki jumlah elemen 8 (4, 2).

**array.vstack**

Metode ini dilakukan untuk menumpuk beberapa array secara vertikal.

In [29]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

**array.hstack**

Metode ini dilakukan untuk menumpuk beberapa array secara horizontal.


In [30]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)

print(np.hstack((h1, h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


#**Representasi Matriks Pada Phyton**

Matriks adalah array 2 dimensi khusus yang mempertahankan sifat 2 dimensinnya melalui operasi. Matriks memiliki operator
khusus tertentu, seperti perkalian matriks dan pemangkatan matriks.

Berikut adalah beberapa penulisan python di berbagai platform:

Berikut contoh penulisan matriks pada python:

In [31]:
import numpy as np

In [32]:
A = np.array([[1, 2], [4, 5]])
A

array([[1, 2],
       [4, 5]])

In [33]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#**Operasi Matriks Pada Phyton**

In [34]:
P = np.array([[1, 2], [4, 5]])
P

array([[1, 2],
       [4, 5]])

In [35]:
Q = np.array([[7, 8], [9, 10]])
Q

array([[ 7,  8],
       [ 9, 10]])

In [36]:
a = 29
a

29

**Penjumlahan Matriks**

In [37]:
np.add(P, Q)

array([[ 8, 10],
       [13, 15]])

**Pengurangan Matriks**

In [38]:
np.subtract(P, Q)

array([[-6, -6],
       [-5, -5]])

**Perkalian Skalar Matriks**

In [39]:
a*P

array([[ 29,  58],
       [116, 145]])

**Perkalian Matriks**

In [40]:
np.multiply(P, Q)

array([[ 7, 16],
       [36, 50]])

**Perkalian Titik Matriks (Dot Product)**

In [41]:
np.dot(P, Q)

array([[25, 28],
       [73, 82]])

**Transpose Matriks**

In [42]:
P.T

array([[1, 4],
       [2, 5]])

**Operasi Fungsi Pada Setiap Elemen Matriks - Akar Kuadrat**

In [43]:
np.sqrt(P)

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

**Menjumlahkan Semua Elemen Kolom Sebuah Matriks**

In [44]:
Q

array([[ 7,  8],
       [ 9, 10]])

In [45]:
np.sum(Q, axis = 1)

array([15, 19])

**Menjumlahkan Semua Elemen Baris Sebuah Matriks**

In [46]:
np.sum(Q, axis = 0)

array([16, 18])

#**Aljabar Linear Pada Phyton**

Dalam modul numpy juga disediakan fungsi-fungsi Aljabar Linear untuk matriks. Beberapa konsep Aljabar Linear yang akan
ditunjukkan di modul ini adalah :

*   Determinan
*   Inverse
*   Nilai Eigen
*   Vector Eigen
*   Matriks Identitas
*   Matriks Satuan
*   Matriks Nol
*   Matriks Segitiga L dan U
*   Dekomposisi L U matriks


In [47]:
A = np.array([[2, 3, 4], [7, 8, 9], [10, 7, 8]])
A

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [10,  7,  8]])

In [48]:
B = np.array([[5, 7, 4], [6, 8, 9], [1, 2, 6]])
B

array([[5, 7, 4],
       [6, 8, 9],
       [1, 2, 6]])

**Determinan**

In [49]:
np.linalg.det(A)

-20.000000000000007

**Inverse Matriks**

In [50]:
np.linalg.inv(A)

array([[-0.05, -0.2 ,  0.25],
       [-1.7 ,  1.2 , -0.5 ],
       [ 1.55, -0.8 ,  0.25]])

**Nilai Eigen dan Vector Eigen**

In [51]:
eig, vec_eig = np.linalg.eig(A)
print('Nilai eigen matriks A:')
print(eig)
print('Vektor eigen matriks A:')
print(vec_eig)

Nilai eigen matriks A:
[19.39079317 -1.9262474   0.53545423]
Vektor eigen matriks A:
[[-0.27295093 -0.54761756  0.15754422]
 [-0.6940728  -0.31621014 -0.8168342 ]
 [-0.66615369  0.7746781   0.55494297]]


**Matriks Identitas**

In [52]:
Identitas=np.identity(5)
print(Identitas)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
Identitas[:,3]

array([0., 0., 0., 1., 0.])

**Matriks Satuan**

In [54]:
Satuan=np.ones((2, 3))
Satuan

array([[1., 1., 1.],
       [1., 1., 1.]])

**Matriks Nol**

In [55]:
MatriksNol=np.zeros(10)
MatriksNol

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Matriks Segitiga Atas dan Bawah**

In [56]:
M=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
Lower=np.tril(M, -1)
Lower

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [58]:
Upper=np.triu(M, 1)
Upper

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

#**Latihan**

1. Buatlah array matriks identitas dengan ukuran 20x20!


In [59]:
Identitas=np.identity(20)
print(Identitas)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

2. Buatlah array matriks dengan ukuran sesuai dengan array c dan dengan elemennya adalah bilangan 112!


In [60]:
c=[20, 60, 50, 70, 90, 78, 46, 56]
c = np.array([20, 60, 50, 70, 90, 78, 46, 56])
print(c)
print(np.full_like(c,112))

[20 60 50 70 90 78 46 56]
[112 112 112 112 112 112 112 112]
